In [1]:
import sys
from pathlib import Path
from pyprojroot import here

sys.path.append(str(here()))

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from src.config import cfg
from src.my_utils import set_seed, build_preproc_pipeline, cv_result, log_experiment

from sklearn.model_selection import StratifiedKFold, RepeatedStratifiedKFold

from lightgbm import LGBMClassifier

from src.features import *
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
gseed = cfg.general.seed
set_seed(gseed)

In [4]:
train_path = Path(cfg.paths.train)
submit_path = Path(cfg.paths.test)

In [5]:
df_train = pd.read_csv(train_path)
df_submit = pd.read_csv(submit_path)

In [6]:
X_train = df_train.drop(columns=["Survived"])
y_train = df_train["Survived"]

In [7]:
# skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=gseed)

# в связи с шумом и малым числом данных лучше перейти на repeated версию
rskf = RepeatedStratifiedKFold(n_splits=10, n_repeats=5, random_state=gseed)

# consistent model

Базовая модель, которая не склонна к переобучению как бустинг

In [8]:
base = RandomForestClassifier(
    n_estimators=300, max_depth=5, min_samples_split=10, random_state=gseed
)

In [82]:
preproc = build_preproc_pipeline(
    age_imputer=BaselineAgeImputer(),
    cabin_transformer=BaselineCabinTransformer(),
    group_transformer="passthrough",
    cat_encoder=OneHotEncoder(sparse_output=False, drop="first"),
    num_scaler="passthrough",
    cat_columns=["Pclass", "Sex", "Embarked"],
    num_columns=["Age", "SibSp", "Parch", "Fare"],
)
preproc

Pipeline(steps=[('dtypes', DtypesTransformer()),
                ('title_transformer', TitleTransformer()),
                ('age_imputer', BaselineAgeImputer()),
                ('embarked_imputer', EmbarkedImputer()),
                ('fare_imputer', BaselineFareImputer()),
                ('group_transformer', 'passthrough'),
                ('cabin_transformer', BaselineCabinTransformer()),
                ('column_transformer',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['Pclass', 'Sex',
                                                   'Embarked']),
                                                 ('num', 'passthrough',
                                                  ['Age', 'SibSp', 'Parch',
                                                   'Fare'])],
                                   verbose_feature_names_out=False))])

In [83]:
_, _, metrics = cv_result(base, X_train, y_train, rskf, preproc)
metrics

   TRAIN_acc_MEAN  TRAIN_acc_STD  VAL_acc_MEAN  VAL_acc_STD   OOF_acc
0        0.847762       0.005326      0.831428     0.030982  0.830527

In [84]:
metrics_dict = metrics.iloc[0].to_dict()
log_experiment(
    model_name="consistent model",
    metrics=metrics_dict,
    note="consistent model",
)

### Age imputers

In [85]:
metrics_lst = []
for age_imputer in (
    BaselineAgeImputer(),
    ByPclassAgeImputer(),
    BySexAgeImputer(),
    BySexPclassAgeImputer(),
    ByPclassTitleAgeImputer(),
):
    preproc = build_preproc_pipeline(
        age_imputer=age_imputer,
        cabin_transformer=BaselineCabinTransformer(),
        group_transformer="passthrough",
        cat_encoder=OneHotEncoder(sparse_output=False, drop="first"),
        num_scaler="passthrough",
        cat_columns=["Pclass", "Sex", "Embarked"],
        num_columns=["Age", "SibSp", "Parch", "Fare"],
    )

    _, _, metrics = cv_result(base, X_train, y_train, rskf, preproc)
    print(metrics)
    metrics_dict = metrics.iloc[0].to_dict()
    metrics_lst.append(metrics_dict)

   TRAIN_acc_MEAN  TRAIN_acc_STD  VAL_acc_MEAN  VAL_acc_STD   OOF_acc
0        0.847762       0.005326      0.831428     0.030982  0.830527
   TRAIN_acc_MEAN  TRAIN_acc_STD  VAL_acc_MEAN  VAL_acc_STD   OOF_acc
0        0.847762       0.005075      0.832105      0.03092  0.832772
   TRAIN_acc_MEAN  TRAIN_acc_STD  VAL_acc_MEAN  VAL_acc_STD   OOF_acc
0        0.849183       0.005308      0.828969     0.032438  0.830527
   TRAIN_acc_MEAN  TRAIN_acc_STD  VAL_acc_MEAN  VAL_acc_STD  OOF_acc
0        0.848809       0.005352      0.830984     0.031111  0.83165
   TRAIN_acc_MEAN  TRAIN_acc_STD  VAL_acc_MEAN  VAL_acc_STD   OOF_acc
0        0.852052       0.005133      0.832552     0.030011  0.830527

In [86]:
log_experiment(
    model_name="consistent model",
    metrics=metrics_lst[1],
    note="most effect - ByPclassAgeImputer",
)

### Title

In [87]:
preproc = build_preproc_pipeline(
    age_imputer=BaselineAgeImputer(),
    cabin_transformer=BaselineCabinTransformer(),
    group_transformer="passthrough",
    cat_encoder=OneHotEncoder(sparse_output=False, drop="first"),
    num_scaler="passthrough",
    cat_columns=["Pclass", "Sex", "Embarked"] + ["Title"],
    num_columns=["Age", "SibSp", "Parch", "Fare"],
)
preproc

Pipeline(steps=[('dtypes', DtypesTransformer()),
                ('title_transformer', TitleTransformer()),
                ('age_imputer', BaselineAgeImputer()),
                ('embarked_imputer', EmbarkedImputer()),
                ('fare_imputer', BaselineFareImputer()),
                ('group_transformer', 'passthrough'),
                ('cabin_transformer', BaselineCabinTransformer()),
                ('column_transformer',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['Pclass', 'Sex', 'Embarked',
                                                   'Title']),
                                                 ('num', 'passthrough',
                                                  ['Age', 'SibSp', 'Parch',
                                                   'Fare'])],
                                   verbose_feature_names_out=False))])

In [88]:
_, _, metrics = cv_result(base, X_train, y_train, rskf, preproc)
metrics  # титул бесполезен

   TRAIN_acc_MEAN  TRAIN_acc_STD  VAL_acc_MEAN  VAL_acc_STD  OOF_acc
0          0.8526       0.004231      0.827156     0.037338  0.82716

In [89]:
metrics_dict = metrics.iloc[0].to_dict()
log_experiment(
    model_name="consistent model",
    metrics=metrics_dict,
    note="Title - useless",
)

### Ticket_Group_Size

In [90]:
preproc = build_preproc_pipeline(
    age_imputer=BaselineAgeImputer(),
    cabin_transformer=BaselineCabinTransformer(),
    group_transformer=GroupTransformer(),
    cat_encoder=OneHotEncoder(sparse_output=False, drop="first"),
    num_scaler="passthrough",
    cat_columns=["Pclass", "Sex", "Embarked"],
    num_columns=["Age", "SibSp", "Parch", "Fare"] + ["Ticket_Group_Size"],
)
preproc

Pipeline(steps=[('dtypes', DtypesTransformer()),
                ('title_transformer', TitleTransformer()),
                ('age_imputer', BaselineAgeImputer()),
                ('embarked_imputer', EmbarkedImputer()),
                ('fare_imputer', BaselineFareImputer()),
                ('group_transformer', GroupTransformer()),
                ('cabin_transformer', BaselineCabinTransformer()),
                ('column_transformer',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['Pclass', 'Sex',
                                                   'Embarked']),
                                                 ('num', 'passthrough',
                                                  ['Age', 'SibSp', 'Parch',
                                                   'Fare',
                                                   'Ticket_Group_Size'])],
                                   verbose_feature_names_out=False))])

In [91]:
_, _, metrics = cv_result(base, X_train, y_train, rskf, preproc)
metrics  # Ticket_Group_Size не очень полезна

   TRAIN_acc_MEAN  TRAIN_acc_STD  VAL_acc_MEAN  VAL_acc_STD   OOF_acc
0        0.850156       0.005669      0.829196     0.032404  0.828283

In [92]:
metrics_dict = metrics.iloc[0].to_dict()
log_experiment(
    model_name="baseline model",
    metrics=metrics_dict,
    note="Ticket_Group_Size - useless",
)

### Fare, True_Fare, Log_True_Fare

In [93]:
metrics_lst = []
for col in ("Fare", "True_Fare", "Log_True_Fare"):
    preproc = build_preproc_pipeline(
        age_imputer=BaselineAgeImputer(),
        cabin_transformer=BaselineCabinTransformer(),
        group_transformer=GroupTransformer(),
        cat_encoder=OneHotEncoder(sparse_output=False, drop="first"),
        num_scaler="passthrough",
        cat_columns=["Pclass", "Sex", "Embarked"],
        num_columns=["Age", "SibSp", "Parch"] + ["Ticket_Group_Size"] + [col],
    )
    # print(preproc)
    _, _, metrics = cv_result(base, X_train, y_train, rskf, preproc)
    print(metrics)
    metrics_dict = metrics.iloc[0].to_dict()
    metrics_lst.append(metrics_dict)

   TRAIN_acc_MEAN  TRAIN_acc_STD  VAL_acc_MEAN  VAL_acc_STD   OOF_acc
0         0.85063       0.005348      0.828067     0.032769  0.835017
   TRAIN_acc_MEAN  TRAIN_acc_STD  VAL_acc_MEAN  VAL_acc_STD  OOF_acc
0         0.84634       0.005477      0.824929     0.032393  0.82716
   TRAIN_acc_MEAN  TRAIN_acc_STD  VAL_acc_MEAN  VAL_acc_STD  OOF_acc
0         0.84634       0.005477      0.824929     0.032393  0.82716

In [94]:
""" добавление одной из колонок сделало хуже
   TRAIN_acc_MEAN  TRAIN_acc_STD  VAL_acc_MEAN  VAL_acc_STD   OOF_acc
0        0.847762       0.005326      0.831428     0.030982  0.830527
   TRAIN_acc_MEAN  TRAIN_acc_STD  VAL_acc_MEAN  VAL_acc_STD   OOF_acc
0        0.845243        0.00459      0.823803     0.029919  0.824916
   TRAIN_acc_MEAN  TRAIN_acc_STD  VAL_acc_MEAN  VAL_acc_STD   OOF_acc
0        0.845243       0.004632      0.823803     0.029919  0.824916
"""

' добавление одной из колонок сделало хуже\n   TRAIN_acc_MEAN  TRAIN_acc_STD  VAL_acc_MEAN  VAL_acc_STD   OOF_acc\n0        0.847762       0.005326      0.831428     0.030982  0.830527\n   TRAIN_acc_MEAN  TRAIN_acc_STD  VAL_acc_MEAN  VAL_acc_STD   OOF_acc\n0        0.845243        0.00459      0.823803     0.029919  0.824916\n   TRAIN_acc_MEAN  TRAIN_acc_STD  VAL_acc_MEAN  VAL_acc_STD   OOF_acc\n0        0.845243       0.004632      0.823803     0.029919  0.824916\n'

In [95]:
log_experiment(
    model_name="consistent model",
    metrics=metrics_lst[0],
    note="most effect - Ticket_Group_Size + base fare",
)

### Ticket_Survival_Rate

In [ ]:
preproc = build_preproc_pipeline(
    age_imputer=BaselineAgeImputer(),
    cabin_transformer=BaselineCabinTransformer(),
    group_transformer=GroupTransformer(smooth=3e-4),
    cat_encoder=OneHotEncoder(sparse_output=False, drop="first"),
    num_scaler="passthrough",
    cat_columns=["Pclass", "Sex", "Embarked"],
    num_columns=["Age", "SibSp", "Parch", "Fare"] + ["Ticket_Survival_Rate"],
)
preproc

Pipeline(steps=[('dtypes', DtypesTransformer()),
                ('title_transformer', TitleTransformer()),
                ('age_imputer', BaselineAgeImputer()),
                ('embarked_imputer', EmbarkedImputer()),
                ('fare_imputer', BaselineFareImputer()),
                ('group_transformer', GroupTransformer(smooth=0.0003)),
                ('cabin_transformer', BaselineCabinTransformer()),
                ('column_transformer',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['Pclass', 'Sex',
                                                   'Embarked']),
                                                 ('num', 'passthrough',
                                                  ['Age', 'SibSp', 'Parch',
                                                   'Fare',
                                                   'Ticket_Survival_Rate'])],
                                   verbose_feature_names_out=False))])

In [170]:
_, _, metrics = cv_result(base, X_train, y_train, rskf, preproc)
metrics

   TRAIN_acc_MEAN  TRAIN_acc_STD  VAL_acc_MEAN  VAL_acc_STD   OOF_acc
0        0.890785       0.006394      0.833236     0.033217  0.833895

In [174]:
metrics_dict = metrics.iloc[0].to_dict()
log_experiment(
    model_name="consistent model",
    metrics=metrics_dict,
    note="Ticket_Survival_Rate useful with low smooth",
)

### Deck + Has_Cabin

In [ ]:
preproc = build_preproc_pipeline(
    age_imputer=BaselineAgeImputer(),
    cabin_transformer=AdvancedCabinTransformer(),
    group_transformer="passthrough",
    cat_encoder=OneHotEncoder(sparse_output=False, drop="first"),
    num_scaler="passthrough",
    cat_columns=["Pclass", "Sex", "Embarked"],
    num_columns=["Age", "SibSp", "Parch", "Fare"],
)
preproc

Pipeline(steps=[('dtypes', DtypesTransformer()),
                ('title_transformer', TitleTransformer()),
                ('age_imputer', BaselineAgeImputer()),
                ('embarked_imputer', EmbarkedImputer()),
                ('fare_imputer', BaselineFareImputer()),
                ('group_transformer', 'passthrough'),
                ('cabin_transformer', AdvancedCabinTransformer()),
                ('column_transformer',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['Pclass', 'Sex', 'Embarked',
                                                   'Deck', 'Has_Cabin']),
                                                 ('num', 'passthrough',
                                                  ['Age', 'SibSp', 'Parch',
                                                   'Fare'])],
                                   verbose_feature_names_out=False))])

In [110]:
_, _, metrics = cv_result(base, X_train, y_train, rskf, preproc)
metrics

   TRAIN_acc_MEAN  TRAIN_acc_STD  VAL_acc_MEAN  VAL_acc_STD   OOF_acc
0        0.855269       0.004188      0.819551     0.034777  0.821549

In [111]:
metrics_dict = metrics.iloc[0].to_dict()
log_experiment(
    model_name="consistent model",
    metrics=metrics_dict,
    note="Has_Cabin & Deck - useless",
)

### optimal features

Ticket_Group_Size + base fare + ByPclassAgeImputer + Ticket_Survival_Rate

In [ ]:
preproc = build_preproc_pipeline(
    age_imputer=ByPclassAgeImputer(),
    cabin_transformer=BaselineCabinTransformer(),
    group_transformer=GroupTransformer(smooth=1e-5),
    cat_encoder=OneHotEncoder(sparse_output=False, drop="first"),
    num_scaler="passthrough",
    cat_columns=["Pclass", "Sex", "Embarked"],
    num_columns=[
        "Age",
        "SibSp",
        "Parch",
        "Ticket_Group_Size",
        "Fare",
        "Ticket_Survival_Rate",
    ],
)
preproc

Pipeline(steps=[('dtypes', DtypesTransformer()),
                ('title_transformer', TitleTransformer()),
                ('age_imputer', ByPclassAgeImputer()),
                ('embarked_imputer', EmbarkedImputer()),
                ('fare_imputer', BaselineFareImputer()),
                ('group_transformer', GroupTransformer(smooth=1e-05)),
                ('cabin_transformer', BaselineCabinTransformer()),
                ('column_transformer',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['Pclass', 'Sex',
                                                   'Embarked']),
                                                 ('num', 'passthrough',
                                                  ['Age', 'SibSp', 'Parch',
                                                   'Ticket_Group_Size', 'Fare',
                                                   'Ticket_Survival_Rate'])],
                                   verbose_feature_names_out=False))])

In [172]:
_, _, metrics = cv_result(base, X_train, y_train, rskf, preproc)
metrics

   TRAIN_acc_MEAN  TRAIN_acc_STD  VAL_acc_MEAN  VAL_acc_STD   OOF_acc
0        0.890535       0.005986      0.833011     0.030079  0.836139

In [ ]:
metrics_dict = metrics.iloc[0].to_dict()
log_experiment(
    model_name="consistent model",
    metrics=metrics_dict,
    note="all optimal features (Ticket_Group_Size + base fare + ByPclassAgeImputer + Ticket_Survival_Rate) together are actually good",
)

### random manual experiments

In [ ]:
preproc = build_preproc_pipeline(
    age_imputer=ByPclassAgeImputer(),
    cabin_transformer=AdvancedCabinTransformer(),
    group_transformer=GroupTransformer(smooth=1e-5),
    cat_encoder=OneHotEncoder(sparse_output=False, drop="first"),
    num_scaler="passthrough",
    cat_columns=["Pclass", "Sex", "Title", "Has_Cabin"],
    num_columns=[
        "Age",
        "Ticket_Group_Size",
        "Fare",
        "Ticket_Survival_Rate",
    ],
)
preproc

Pipeline(steps=[('dtypes', DtypesTransformer()),
                ('title_transformer', TitleTransformer()),
                ('age_imputer', ByPclassAgeImputer()),
                ('embarked_imputer', EmbarkedImputer()),
                ('fare_imputer', BaselineFareImputer()),
                ('group_transformer', GroupTransformer(smooth=1e-05)),
                ('cabin_transformer', AdvancedCabinTransformer()),
                ('column_transformer',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['Pclass', 'Sex', 'Title',
                                                   'Has_Cabin']),
                                                 ('num', 'passthrough',
                                                  ['Age', 'Ticket_Group_Size',
                                                   'Fare',
                                                   'Ticket_Survival_Rate'])],
                                   verbose_feature_names_out=False))])

In [200]:
_, _, metrics = cv_result(base, X_train, y_train, rskf, preproc)
metrics  # один из случайных ручных экспериментов оказался дейстительно удачным

   TRAIN_acc_MEAN  TRAIN_acc_STD  VAL_acc_MEAN  VAL_acc_STD   OOF_acc
0        0.889463       0.007554      0.840849     0.036907  0.843996

In [201]:
metrics_dict = metrics.iloc[0].to_dict()
log_experiment(
    model_name="consistent model",
    metrics=metrics_dict,
    note="prev best + Has_Cabin",
)

In [9]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
preprocessor = Pipeline(
    [
        ("dtypes", DtypesTransformer()),
        ("title_transformer", TitleTransformer()),
        ("age_imputer", ByPclassAgeImputer()),
        ("embarked_imputer", EmbarkedImputer()),
        ("fare_imputer", FareImputer()),
        ("group_transformer", GroupTransformer(smooth=1e-6)),
        ("cabin_transformer", AdvancedCabinTransformer()),
        (
            "column_transformer",
            ColumnTransformer(
                [
                    (
                        "cat_ohe",
                        OneHotEncoder(sparse_output=False, drop="first"),
                        ["Pclass", "Sex", "Title", "Has_Cabin"],
                    ),
                    (
                        "cat_ordinal",
                        Pipeline(
                            [
                                ("binner", QuantileBinner(5)),
                                ("ordinal_encoder", OrdinalEncoder()),
                            ]
                        ),
                        ["Fare"],
                    ),
                    (
                        "num",
                        "passthrough",
                        ["Age", "Ticket_Group_Size", "Ticket_Survival_Rate"],
                    ),
                ],
                remainder="drop",
                verbose_feature_names_out=False,
            ).set_output(transform="pandas"),
        ),
    ]
)

In [ ]:
_, _, metrics = cv_result(base, X_train, y_train, rskf, preprocessor)
metrics  # стало хуже, бины не помогли

   TRAIN_acc_MEAN  TRAIN_acc_STD  VAL_acc_MEAN  VAL_acc_STD   OOF_acc
0        0.886719       0.007606      0.836579     0.037502  0.837262

В ходе экспериментов и методом случайного тыка оптимальный процесс предобработки данных
```python
preproc = build_preproc_pipeline(
    age_imputer=ByPclassAgeImputer(),
    cabin_transformer=AdvancedCabinTransformer(),
    group_transformer=GroupTransformer(smooth=1e-5),
    cat_encoder=OneHotEncoder(sparse_output=False, drop="first"),
    num_scaler="passthrough",
    cat_columns=["Pclass", "Sex", "Title", 'Has_Cabin'],
    num_columns=[
        "Age",
        "Ticket_Group_Size",
        "Fare",
        "Ticket_Survival_Rate",
    ],
)
preproc

```

In [202]:
log_dir = Path(cfg.paths.logs)
log_file_path = log_dir / "experiments.log"

df_raw = pd.read_json(log_file_path, lines=True)

df_metrics = pd.json_normalize(df_raw["metrics"])

df = pd.concat([df_raw.drop(columns=["metrics"]), df_metrics], axis=1)

df.sort_values(
    by=["OOF_acc", "VAL_acc_MEAN", "VAL_acc_STD"], ascending=[False, False, True]
)

,timestamp,model,note,TRAIN_acc_MEAN,TRAIN_acc_STD,VAL_acc_MEAN,VAL_acc_STD,OOF_acc
11,2026-09-05 17:56:00,consistent model,prev best + Has_Cabin,0.889463,0.007554,0.840849,0.036907,0.843996
10,2026-09-05 17:13:28,consistent model,"best ever result, created randomly and manually",0.893304,0.005404,0.839733,0.036428,0.842873
8,2026-09-05 16:59:19,consistent model,all optimal features (Ticket_Group_Size + base...,0.890535,0.005986,0.833011,0.030079,0.836139
9,2026-09-05 17:00:03,consistent model,Ticket_Survival_Rate useful with low smooth,0.890535,0.005986,0.833011,0.030079,0.836139
7,2026-09-05 11:34:24,consistent model,all optimal features (Ticket_Group_Size + base...,0.850854,0.005395,0.829640,0.032312,0.835017
4,2026-09-05 11:15:16,consistent model,most effect - Ticket_Group_Size + base fare,0.850630,0.005348,0.828067,0.032769,0.835017
1,2026-09-05 11:13:04,consistent model,most effect - ByPclassAgeImputer,0.847762,0.005075,0.832105,0.030920,0.832772
0,2026-09-05 11:11:00,consistent model,consistent model,0.847762,0.005326,0.831428,0.030982,0.830527
5,2026-09-05 11:15:46,consistent model,Ticket_Survival_Rate useless,0.892231,0.006461,0.830991,0.033170,0.830527
3,2026-09-05 11:13:48,baseline model,Ticket_Group_Size - useless,0.850156,0.005669,0.829196,0.032404,0.828283
2,2026-09-05 11:13:25,consistent model,Title - useless,0.852600,0.004231,0.827156,0.037338,0.827160
6,2026-09-05 11:21:48,consistent model,Has_Cabin & Deck - useless,0.855269,0.004188,0.819551,0.034777,0.821549