In [31]:
import sys
from pathlib import Path
from pyprojroot import here

sys.path.append(str(here()))

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from src.config import cfg
from src.my_utils import set_seed, cv_result, log_experiment, make_submit

from sklearn.model_selection import RepeatedStratifiedKFold

from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

from src.features import *
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [32]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [17]:
gseed = cfg.general.seed
set_seed(gseed)

In [18]:
train_path = Path(cfg.paths.train)
submit_path = Path(cfg.paths.test)

In [19]:
df_train = pd.read_csv(train_path)
df_submit = pd.read_csv(submit_path)

In [20]:
X_train = df_train.drop(columns=["Survived"])
y_train = df_train["Survived"]

In [21]:
rskf = RepeatedStratifiedKFold(n_splits=10, n_repeats=5, random_state=gseed)

In [22]:
preprocessor = Pipeline(
    [
        ("dtypes", DtypesTransformer()),
        ("title_transformer", TitleTransformer()),
        ("age_imputer", ByPclassAgeImputer()),
        ("embarked_imputer", EmbarkedImputer()),
        ("fare_imputer", FareImputer()),
        ("group_transformer", GroupTransformer(smooth=1e-6)),
        ("cabin_transformer", AdvancedCabinTransformer()),
        (
            "column_transformer",
            ColumnTransformer(
                [
                    (
                        "cat_ohe",
                        OneHotEncoder(sparse_output=False, drop="first"),
                        ["Pclass", "Sex", "Title", "Has_Cabin"],
                    ),
                    (
                        "num",
                        "passthrough",
                        ["Age", "Ticket_Group_Size", "Fare", "Ticket_Survival_Rate"],
                    ),
                ],
                remainder="drop",
                verbose_feature_names_out=False,
            ).set_output(transform="pandas"),
        ),
    ]
)

### consistent model

In [23]:
base = RandomForestClassifier(
    n_estimators=300, max_depth=5, min_samples_split=10, random_state=gseed
)

In [24]:
_, _, metrics = cv_result(base, X_train, y_train, rskf, preprocessor)
metrics

   TRAIN_acc_MEAN  TRAIN_acc_STD  VAL_acc_MEAN  VAL_acc_STD   OOF_acc
0        0.890311       0.006919      0.840849     0.036838  0.845118

In [ ]:
make_submit(base, preprocessor, X_train, y_train, df_submit, "rfc_final_features.csv")

Файл успешно сохранен: d:\vs_projects\fp_titanic\data\external\rfc_final_features.csv

### baseline lgbm

In [26]:
baseline_model = LGBMClassifier(random_state=gseed, max_depth=7)

In [27]:
_, _, metrics = cv_result(baseline_model, X_train, y_train, rskf, preprocessor)
metrics

[LightGBM] [Info] Number of positive: 307, number of negative: 494
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000291 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 229
[LightGBM] [Info] Number of data points in the train set: 801, number of used features: 12
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.383271 -> initscore=-0.475688
[LightGBM] [Info] Start training from score -0.475688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 308, number of negative: 494
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000066 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 230
[LightGBM] [Info] Number of data points in the train set: 802, number of used features: 12
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.384040 -> initscore=-0.472436
[LightGBM] [Info] Start training from score -0.472436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 308, number of negative: 494
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000067 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 228
[LightGBM] [Info] Number of data points in the train set: 802, number of used features: 12
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.384040 -> initscore=-0.472436
[LightGBM] [Info] Start training from score -0.472436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

   TRAIN_acc_MEAN  TRAIN_acc_STD  VAL_acc_MEAN  VAL_acc_STD   OOF_acc
0        0.942462       0.008384      0.843106     0.036359  0.842873

In [ ]:
make_submit(
    base, preprocessor, X_train, y_train, df_submit, "bl_no_tune_final_features.csv"
)

Файл успешно сохранен: d:\vs_projects\fp_titanic\data\external\bl_no_tune_final_features.csv

### no tune catboost

In [ ]:
baseline_model = CatBoostClassifier(random_seed=gseed)

In [51]:
_, _, metrics = cv_result(baseline_model, X_train, y_train, rskf, preprocessor)
metrics

Learning rate set to 0.009371
0:	learn: 0.6861129	total: 1.61ms	remaining: 1.61s
1:	learn: 0.6790595	total: 3.14ms	remaining: 1.57s
2:	learn: 0.6728121	total: 4.46ms	remaining: 1.48s
3:	learn: 0.6661493	total: 5.59ms	remaining: 1.39s
4:	learn: 0.6596805	total: 6.7ms	remaining: 1.33s
5:	learn: 0.6532724	total: 7.83ms	remaining: 1.3s
6:	learn: 0.6476014	total: 8.9ms	remaining: 1.26s
7:	learn: 0.6423734	total: 9.96ms	remaining: 1.23s
8:	learn: 0.6365185	total: 11ms	remaining: 1.21s
9:	learn: 0.6309801	total: 12.1ms	remaining: 1.2s
10:	learn: 0.6255269	total: 13.3ms	remaining: 1.19s
11:	learn: 0.6205036	total: 14.1ms	remaining: 1.16s
12:	learn: 0.6152816	total: 15.1ms	remaining: 1.15s
13:	learn: 0.6099207	total: 16.2ms	remaining: 1.14s
14:	learn: 0.6057070	total: 17.7ms	remaining: 1.16s
15:	learn: 0.6009370	total: 19.1ms	remaining: 1.18s
16:	learn: 0.5970302	total: 20.4ms	remaining: 1.18s
17:	learn: 0.5925956	total: 21.5ms	remaining: 1.17s
18:	learn: 0.5872791	total: 22.6ms	remaining: 1.17s
19:	learn: 0.5842441	total: 23.3ms	remaining: 1.14s
20:	learn: 0.5807867	total: 24.5ms	remaining: 1.14s
21:	learn: 0.5758203	total: 25.7ms	remaining: 1.14s
22:	learn: 0.5708431	total: 26.8ms	remaining: 1.14s
23:	learn: 0.5663723	total: 27.9ms	remaining: 1.14s
24:	learn: 0.5624448	total: 29ms	remaining: 1.13s
25:	learn: 0.5589593	total: 30.1ms	remaining: 1.13s
26:	learn: 0.5549298	total: 31ms	remaining: 1.12s
27:	learn: 0.5508871	total: 32.6ms	remaining: 1.13s
28:	learn: 0.5477507	total: 34ms	remaining: 1.14s
29:	learn: 0.5441179	total: 35.5ms	remaining: 1.15s
30:	learn: 0.5408583	total: 36.6ms	remaining: 1.14s
31:	learn: 0.5370586	total: 37.7ms	remaining: 1.14s
32:	learn: 0.5337450	total: 38.8ms	remaining: 1.14s
33:	learn: 0.5307880	total: 39.9ms	remaining: 1.13s
34:	learn: 0.5275914	total: 41ms	remaining: 1.13s
35:	learn: 0.5242251	total: 42.1ms	remaining: 1.13s
36:	learn: 0.5211810	total: 43.3ms	remaining: 1.13s
37:	learn: 0.5179916	total: 44.4ms	remaining: 1.12s
38:	learn: 0.5158932	total: 45.5ms	remaining: 1.12s
39:	learn: 0.5132280	total: 46.7ms	remaining: 1.12s
40:	learn: 0.5104161	total: 47.7ms	remaining: 1.12s
41:	learn: 0.5074831	total: 49.2ms	remaining: 1.12s
42:	learn: 0.5045224	total: 50.5ms	remaining: 1.12s
43:	learn: 0.5012854	total: 51.8ms	remaining: 1.13s
44:	learn: 0.4984270	total: 53.2ms	remaining: 1.13s
45:	learn: 0.4961273	total: 54.6ms	remaining: 1.13s
46:	learn: 0.4933165	total: 55.9ms	remaining: 1.13s
47:	learn: 0.4906127	total: 57.3ms	remaining: 1.14s
48:	learn: 0.4880795	total: 58.5ms	remaining: 1.14s
49:	learn: 0.4854796	total: 59.6ms	remaining: 1.13s
50:	learn: 0.4828279	total: 60.7ms	remaining: 1.13s
51:	learn: 0.4807564	total: 61.8ms	remaining: 1.13s
52:	learn: 0.4787114	total: 63.3ms	remaining: 1.13s
53:	learn: 0.4764424	total: 64.5ms	remaining: 1.13s
54:	learn: 0.4745019	total: 66.1ms	remaining: 1.14s
55:	learn: 0.4719937	total: 67.9ms	remaining: 1.15s
56:	learn: 0.4698013	total: 69.2ms	remaining: 1.14s
57:	learn: 0.4676471	total: 70.4ms	remaining: 1.14s
58:	learn: 0.4653095	total: 71.6ms	remaining: 1.14s
59:	learn: 0.4633527	total: 72.7ms	remaining: 1.14s
60:	learn: 0.4611040	total: 74ms	remaining: 1.14s
61:	learn: 0.4591601	total: 75.2ms	remaining: 1.14s
62:	learn: 0.4574455	total: 76.4ms	remaining: 1.14s
63:	learn: 0.4555511	total: 77.5ms	remaining: 1.13s
64:	learn: 0.4545487	total: 78.1ms	remaining: 1.12s
65:	learn: 0.4528460	total: 79.3ms	remaining: 1.12s
66:	learn: 0.4511661	total: 80.7ms	remaining: 1.12s
67:	learn: 0.4492374	total: 82.2ms	remaining: 1.13s
68:	learn: 0.4475268	total: 84.1ms	remaining: 1.14s
69:	learn: 0.4458639	total: 85.6ms	remaining: 1.14s
70:	learn: 0.4442702	total: 86.7ms	remaining: 1.13s
71:	learn: 0.4422380	total: 87.9ms	remaining: 1.13s
72:	learn: 0.4408085	total: 88.9ms	remaining: 1.13s
73:	learn: 0.4401058	total: 89.5ms	remaining: 1.12s
74:	learn: 0.4389638	total: 90.2ms	remaining: 1.11s
75:	learn: 0.4376717	total: 91.4ms	remaining: 1.11s
76:	learn: 0.4361398	total: 92.5ms	remaining: 1.11s
77:	learn: 0.4348195	total: 93.7ms	remaining: 1.11s
78:	learn: 0.4333670	total: 95ms	remaining: 1.11s
79:	learn: 0.4316568	total: 96.3ms	remaining: 1.11s
80:	learn: 0.4302887	total: 97.9ms	remaining: 1.11s
81:	learn: 0.4287433	total: 99.7ms	remaining: 1.11s
82:	learn: 0.4272466	total: 101ms	remaining: 1.11s
83:	learn: 0.4256862	total: 102ms	remaining: 1.11s
84:	learn: 0.4241815	total: 103ms	remaining: 1.11s
85:	learn: 0.4225535	total: 104ms	remaining: 1.11s
86:	learn: 0.4211105	total: 106ms	remaining: 1.11s
87:	learn: 0.4202014	total: 106ms	remaining: 1.1s
88:	learn: 0.4185977	total: 108ms	remaining: 1.1s
89:	learn: 0.4174343	total: 109ms	remaining: 1.1s
90:	learn: 0.4169575	total: 109ms	remaining: 1.09s
91:	learn: 0.4159656	total: 111ms	remaining: 1.09s
92:	learn: 0.4151606	total: 112ms	remaining: 1.09s
93:	learn: 0.4140346	total: 114ms	remaining: 1.09s
94:	learn: 0.4127356	total: 115ms	remaining: 1.09s
95:	learn: 0.4116614	total: 116ms	remaining: 1.09s
96:	learn: 0.4106807	total: 117ms	remaining: 1.09s
97:	learn: 0.4092970	total: 118ms	remaining: 1.09s
98:	learn: 0.4083039	total: 119ms	remaining: 1.09s
99:	learn: 0.4073447	total: 121ms	remaining: 1.08s
100:	learn: 0.4064295	total: 121ms	remaining: 1.08s
101:	learn: 0.4052883	total: 122ms	remaining: 1.08s
102:	learn: 0.4042966	total: 124ms	remaining: 1.08s
103:	learn: 0.4037458	total: 125ms	remaining: 1.08s
104:	learn: 0.4030222	total: 127ms	remaining: 1.08s
105:	learn: 0.4020109	total: 129ms	remaining: 1.09s
106:	learn: 0.4010153	total: 131ms	remaining: 1.09s
107:	learn: 0.3999113	total: 132ms	remaining: 1.09s
108:	learn: 0.3990734	total: 133ms	remaining: 1.09s
109:	learn: 0.3980773	total: 134ms	remaining: 1.09s
110:	learn: 0.3974687	total: 135ms	remaining: 1.08s
111:	learn: 0.3965442	total: 137ms	remaining: 1.08s
112:	learn: 0.3954943	total: 138ms	remaining: 1.08s
113:	learn: 0.3948742	total: 139ms	remaining: 1.08s
114:	learn: 0.3941308	total: 141ms	remaining: 1.08s
115:	learn: 0.3935111	total: 142ms	remaining: 1.08s
116:	learn: 0.3927401	total: 144ms	remaining: 1.08s
117:	learn: 0.3924587	total: 145ms	remaining: 1.08s
118:	learn: 0.3915921	total: 146ms	remaining: 1.08s
119:	learn: 0.3911526	total: 147ms	remaining: 1.08s
120:	learn: 0.3903816	total: 148ms	remaining: 1.08s
121:	learn: 0.3896644	total: 149ms	remaining: 1.07s
122:	learn: 0.3891484	total: 151ms	remaining: 1.07s
123:	learn: 0.3885718	total: 152ms	remaining: 1.07s
124:	learn: 0.3883385	total: 152ms	remaining: 1.06s
125:	learn: 0.3877688	total: 153ms	remaining: 1.06s
126:	learn: 0.3869257	total: 155ms	remaining: 1.06s
127:	learn: 0.3862350	total: 156ms	remaining: 1.06s
128:	learn: 0.3853527	total: 157ms	remaining: 1.06s
129:	learn: 0.3845802	total: 158ms	remaining: 1.06s
130:	learn: 0.3839988	total: 160ms	remaining: 1.06s
131:	learn: 0.3832764	total: 161ms	remaining: 1.06s
132:	learn: 0.3828699	total: 163ms	remaining: 1.06s
133:	learn: 0.3821687	total: 164ms	remaining: 1.06s
134:	learn: 0.3815418	total: 165ms	remaining: 1.06s
135:	learn: 0.3808162	total: 166ms	remaining: 1.05s
136:	learn: 0.3802954	total: 167ms	remaining: 1.05s
137:	learn: 0.3795738	total: 168ms	remaining: 1.05s
138:	learn: 0.3787407	total: 169ms	remaining: 1.05s
139:	learn: 0.3781222	total: 170ms	remaining: 1.05s
140:	learn: 0.3774487	total: 171ms	remaining: 1.04s
141:	learn: 0.3767453	total: 173ms	remaining: 1.04s
142:	learn: 0.3762360	total: 174ms	remaining: 1.04s
143:	learn: 0.3758386	total: 175ms	remaining: 1.04s
144:	learn: 0.3753511	total: 177ms	remaining: 1.04s
145:	learn: 0.3748610	total: 178ms	remaining: 1.04s
146:	learn: 0.3743618	total: 179ms	remaining: 1.04s
147:	learn: 0.3738980	total: 180ms	remaining: 1.04s
148:	learn: 0.3732287	total: 181ms	remaining: 1.03s
149:	learn: 0.3728547	total: 183ms	remaining: 1.03s
150:	learn: 0.3723974	total: 184ms	remaining: 1.03s
151:	learn: 0.3717722	total: 185ms	remaining: 1.03s
152:	learn: 0.3711916	total: 186ms	remaining: 1.03s
153:	learn: 0.3708897	total: 187ms	remaining: 1.03s
154:	learn: 0.3703536	total: 188ms	remaining: 1.03s
155:	learn: 0.3699678	total: 190ms	remaining: 1.03s
156:	learn: 0.3695779	total: 192ms	remaining: 1.03s
157:	learn: 0.3690090	total: 193ms	remaining: 1.03s
158:	learn: 0.3685214	total: 194ms	remaining: 1.03s
159:	learn: 0.3679428	total: 195ms	remaining: 1.02s
160:	learn: 0.3677623	total: 196ms	remaining: 1.02s
161:	learn: 0.3671386	total: 197ms	remaining: 1.02s
162:	learn: 0.3667235	total: 199ms	remaining: 1.02s
163:	learn: 0.3663600	total: 200ms	remaining: 1.02s
164:	learn: 0.3657426	total: 201ms	remaining: 1.02s
165:	learn: 0.3654273	total: 202ms	remaining: 1.01s
166:	learn: 0.3649199	total: 203ms	remaining: 1.01s
167:	learn: 0.3644486	total: 205ms	remaining: 1.02s
168:	learn: 0.3642289	total: 207ms	remaining: 1.01s
169:	learn: 0.3639002	total: 208ms	remaining: 1.02s
170:	learn: 0.3634223	total: 210ms	remaining: 1.02s
171:	learn: 0.3629691	total: 216ms	remaining: 1.04s
172:	learn: 0.3623147	total: 218ms	remaining: 1.04s
173:	learn: 0.3617788	total: 223ms	remaining: 1.06s
174:	learn: 0.3612500	total: 241ms	remaining: 1.13s
175:	learn: 0.3607916	total: 243ms	remaining: 1.14s
176:	learn: 0.3603924	total: 245ms	remaining: 1.14s
177:	learn: 0.3601483	total: 246ms	remaining: 1.14s
178:	learn: 0.3597576	total: 249ms	remaining: 1.14s
179:	learn: 0.3591900	total: 250ms	remaining: 1.14s
180:	learn: 0.3588823	total: 252ms	remaining: 1.14s
181:	learn: 0.3585105	total: 253ms	remaining: 1.14s
182:	learn: 0.3582886	total: 255ms	remaining: 1.14s
183:	learn: 0.3579896	total: 256ms	remaining: 1.14s
184:	learn: 0.3574340	total: 257ms	remaining: 1.13s
185:	learn: 0.3569064	total: 259ms	remaining: 1.13s
186:	learn: 0.3565742	total: 263ms	remaining: 1.14s
187:	learn: 0.3563118	total: 264ms	remaining: 1.14s
188:	learn: 0.3560196	total: 266ms	remaining: 1.14s
189:	learn: 0.3556770	total: 268ms	remaining: 1.14s
190:	learn: 0.3553165	total: 269ms	remaining: 1.14s
191:	learn: 0.3551232	total: 271ms	remaining: 1.14s
192:	learn: 0.3549221	total: 272ms	remaining: 1.14s
193:	learn: 0.3545272	total: 274ms	remaining: 1.14s
194:	learn: 0.3542377	total: 276ms	remaining: 1.14s
195:	learn: 0.3539428	total: 277ms	remaining: 1.14s
196:	learn: 0.3535554	total: 279ms	remaining: 1.14s
197:	learn: 0.3535045	total: 280ms	remaining: 1.13s
198:	learn: 0.3531971	total: 281ms	remaining: 1.13s
199:	learn: 0.3529731	total: 283ms	remaining: 1.13s
200:	learn: 0.3525261	total: 284ms	remaining: 1.13s
201:	learn: 0.3521796	total: 286ms	remaining: 1.13s
202:	learn: 0.3518274	total: 287ms	remaining: 1.13s
203:	learn: 0.3513733	total: 289ms	remaining: 1.13s
204:	learn: 0.3510970	total: 290ms	remaining: 1.13s
205:	learn: 0.3507365	total: 291ms	remaining: 1.12s
206:	learn: 0.3504999	total: 292ms	remaining: 1.12s
207:	learn: 0.3502031	total: 294ms	remaining: 1.12s
208:	learn: 0.3498642	total: 295ms	remaining: 1.11s
209:	learn: 0.3496101	total: 296ms	remaining: 1.11s
210:	learn: 0.3492674	total: 297ms	remaining: 1.11s
211:	learn: 0.3492452	total: 298ms	remaining: 1.11s
212:	learn: 0.3489025	total: 300ms	remaining: 1.11s
213:	learn: 0.3486845	total: 301ms	remaining: 1.1s
214:	learn: 0.3484132	total: 302ms	remaining: 1.1s
215:	learn: 0.3480733	total: 303ms	remaining: 1.1s
216:	learn: 0.3478758	total: 305ms	remaining: 1.1s
217:	learn: 0.3477419	total: 306ms	remaining: 1.1s
218:	learn: 0.3475325	total: 307ms	remaining: 1.09s
219:	learn: 0.3471409	total: 308ms	remaining: 1.09s
220:	learn: 0.3467995	total: 309ms	remaining: 1.09s
221:	learn: 0.3465717	total: 310ms	remaining: 1.09s
222:	learn: 0.3463926	total: 312ms	remaining: 1.08s
223:	learn: 0.3461889	total: 313ms	remaining: 1.08s
224:	learn: 0.3458978	total: 314ms	remaining: 1.08s
225:	learn: 0.3455859	total: 316ms	remaining: 1.08s
226:	learn: 0.3453547	total: 317ms	remaining: 1.08s
227:	learn: 0.3452027	total: 318ms	remaining: 1.08s
228:	learn: 0.3449491	total: 319ms	remaining: 1.07s
229:	learn: 0.3446765	total: 320ms	remaining: 1.07s
230:	learn: 0.3445748	total: 321ms	remaining: 1.07s
231:	learn: 0.3442851	total: 322ms	remaining: 1.07s
232:	learn: 0.3440939	total: 323ms	remaining: 1.06s
233:	learn: 0.3439219	total: 325ms	remaining: 1.06s
234:	learn: 0.3435825	total: 326ms	remaining: 1.06s
235:	learn: 0.3434196	total: 327ms	remaining: 1.06s
236:	learn: 0.3431556	total: 328ms	remaining: 1.06s
237:	learn: 0.3428074	total: 330ms	remaining: 1.06s
238:	learn: 0.3425265	total: 332ms	remaining: 1.06s
239:	learn: 0.3423855	total: 333ms	remaining: 1.05s
240:	learn: 0.3421401	total: 334ms	remaining: 1.05s
241:	learn: 0.3415323	total: 336ms	remaining: 1.05s
242:	learn: 0.3413266	total: 337ms	remaining: 1.05s
243:	learn: 0.3411557	total: 338ms	remaining: 1.05s
244:	learn: 0.3409121	total: 339ms	remaining: 1.04s
245:	learn: 0.3407800	total: 340ms	remaining: 1.04s
246:	learn: 0.3404372	total: 342ms	remaining: 1.04s
247:	learn: 0.3402786	total: 343ms	remaining: 1.04s
248:	learn: 0.3399595	total: 344ms	remaining: 1.04s
249:	learn: 0.3397129	total: 346ms	remaining: 1.04s
250:	learn: 0.3394303	total: 347ms	remaining: 1.03s
251:	learn: 0.3392444	total: 348ms	remaining: 1.03s
252:	learn: 0.3389973	total: 349ms	remaining: 1.03s
253:	learn: 0.3387046	total: 351ms	remaining: 1.03s
254:	learn: 0.3385257	total: 352ms	remaining: 1.03s
255:	learn: 0.3382623	total: 353ms	remaining: 1.02s
256:	learn: 0.3380097	total: 354ms	remaining: 1.02s
257:	learn: 0.3377948	total: 355ms	remaining: 1.02s
258:	learn: 0.3375144	total: 356ms	remaining: 1.02s
259:	learn: 0.3373870	total: 357ms	remaining: 1.02s
260:	learn: 0.3370782	total: 358ms	remaining: 1.01s
261:	learn: 0.3367750	total: 360ms	remaining: 1.01s
262:	learn: 0.3367394	total: 361ms	remaining: 1.01s
263:	learn: 0.3364970	total: 363ms	remaining: 1.01s
264:	learn: 0.3362196	total: 365ms	remaining: 1.01s
265:	learn: 0.3360021	total: 366ms	remaining: 1.01s
266:	learn: 0.3357598	total: 367ms	remaining: 1.01s
267:	learn: 0.3355521	total: 368ms	remaining: 1s
268:	learn: 0.3353189	total: 369ms	remaining: 1s
269:	learn: 0.3351267	total: 370ms	remaining: 1s
270:	learn: 0.3349124	total: 372ms	remaining: 1000ms
271:	learn: 0.3346745	total: 373ms	remaining: 998ms
272:	learn: 0.3345065	total: 374ms	remaining: 996ms
273:	learn: 0.3343340	total: 375ms	remaining: 995ms
274:	learn: 0.3341132	total: 377ms	remaining: 994ms
275:	learn: 0.3337882	total: 378ms	remaining: 992ms
276:	learn: 0.3334435	total: 380ms	remaining: 992ms
277:	learn: 0.3332366	total: 382ms	remaining: 991ms
278:	learn: 0.3329914	total: 383ms	remaining: 990ms
279:	learn: 0.3326411	total: 384ms	remaining: 988ms
280:	learn: 0.3324284	total: 385ms	remaining: 986ms
281:	learn: 0.3323183	total: 386ms	remaining: 983ms
282:	learn: 0.3320080	total: 387ms	remaining: 981ms
283:	learn: 0.3318680	total: 389ms	remaining: 980ms
284:	learn: 0.3317880	total: 390ms	remaining: 978ms
285:	learn: 0.3316014	total: 391ms	remaining: 976ms
286:	learn: 0.3314044	total: 392ms	remaining: 975ms
287:	learn: 0.3312575	total: 394ms	remaining: 974ms
288:	learn: 0.3309904	total: 396ms	remaining: 974ms
289:	learn: 0.3308535	total: 397ms	remaining: 973ms
290:	learn: 0.3307062	total: 399ms	remaining: 972ms
291:	learn: 0.3304117	total: 400ms	remaining: 970ms
292:	learn: 0.3302057	total: 402ms	remaining: 969ms
293:	learn: 0.3298857	total: 403ms	remaining: 967ms
294:	learn: 0.3297167	total: 404ms	remaining: 966ms
295:	learn: 0.3294390	total: 405ms	remaining: 964ms
296:	learn: 0.3292471	total: 407ms	remaining: 963ms
297:	learn: 0.3291141	total: 408ms	remaining: 962ms
298:	learn: 0.3290198	total: 410ms	remaining: 961ms
299:	learn: 0.3288191	total: 411ms	remaining: 960ms
300:	learn: 0.3285777	total: 412ms	remaining: 958ms
301:	learn: 0.3284613	total: 414ms	remaining: 956ms
302:	learn: 0.3283115	total: 415ms	remaining: 954ms
303:	learn: 0.3282080	total: 416ms	remaining: 952ms
304:	learn: 0.3281184	total: 417ms	remaining: 950ms
305:	learn: 0.3278793	total: 418ms	remaining: 948ms
306:	learn: 0.3276089	total: 419ms	remaining: 946ms
307:	learn: 0.3274367	total: 420ms	remaining: 944ms
308:	learn: 0.3271953	total: 422ms	remaining: 943ms
309:	learn: 0.3270446	total: 423ms	remaining: 942ms
310:	learn: 0.3267392	total: 425ms	remaining: 941ms
311:	learn: 0.3265663	total: 426ms	remaining: 940ms
312:	learn: 0.3265027	total: 427ms	remaining: 938ms
313:	learn: 0.3264787	total: 428ms	remaining: 935ms
314:	learn: 0.3262373	total: 429ms	remaining: 933ms
315:	learn: 0.3262203	total: 430ms	remaining: 930ms
316:	learn: 0.3260690	total: 431ms	remaining: 929ms
317:	learn: 0.3258537	total: 432ms	remaining: 927ms
318:	learn: 0.3257367	total: 433ms	remaining: 925ms
319:	learn: 0.3256634	total: 434ms	remaining: 923ms
320:	learn: 0.3254733	total: 435ms	remaining: 921ms
321:	learn: 0.3253980	total: 436ms	remaining: 919ms
322:	learn: 0.3252843	total: 438ms	remaining: 918ms
323:	learn: 0.3251332	total: 439ms	remaining: 917ms
324:	learn: 0.3250239	total: 441ms	remaining: 915ms
325:	learn: 0.3249298	total: 442ms	remaining: 914ms
326:	learn: 0.3247244	total: 443ms	remaining: 912ms
327:	learn: 0.3246439	total: 444ms	remaining: 910ms
328:	learn: 0.3244716	total: 445ms	remaining: 908ms
329:	learn: 0.3243562	total: 446ms	remaining: 906ms
330:	learn: 0.3241406	total: 447ms	remaining: 904ms
331:	learn: 0.3239543	total: 449ms	remaining: 903ms
332:	learn: 0.3238500	total: 450ms	remaining: 901ms
333:	learn: 0.3236911	total: 451ms	remaining: 899ms
334:	learn: 0.3236424	total: 452ms	remaining: 897ms
335:	learn: 0.3234729	total: 453ms	remaining: 896ms
336:	learn: 0.3234215	total: 455ms	remaining: 895ms
337:	learn: 0.3232843	total: 457ms	remaining: 894ms
338:	learn: 0.3232027	total: 458ms	remaining: 893ms
339:	learn: 0.3230828	total: 459ms	remaining: 891ms
340:	learn: 0.3229409	total: 460ms	remaining: 889ms
341:	learn: 0.3227482	total: 461ms	remaining: 887ms
342:	learn: 0.3225488	total: 462ms	remaining: 885ms
343:	learn: 0.3223939	total: 463ms	remaining: 883ms
344:	learn: 0.3223042	total: 464ms	remaining: 882ms
345:	learn: 0.3220276	total: 465ms	remaining: 880ms
346:	learn: 0.3218579	total: 467ms	remaining: 878ms
347:	learn: 0.3216141	total: 468ms	remaining: 876ms
348:	learn: 0.3214554	total: 469ms	remaining: 875ms
349:	learn: 0.3211590	total: 470ms	remaining: 874ms
350:	learn: 0.3210806	total: 472ms	remaining: 872ms
351:	learn: 0.3209734	total: 473ms	remaining: 871ms
352:	learn: 0.3208193	total: 474ms	remaining: 869ms
353:	learn: 0.3207183	total: 476ms	remaining: 868ms
354:	learn: 0.3206435	total: 477ms	remaining: 866ms
355:	learn: 0.3205144	total: 478ms	remaining: 865ms
356:	learn: 0.3204844	total: 479ms	remaining: 863ms
357:	learn: 0.3204133	total: 480ms	remaining: 861ms
358:	learn: 0.3202867	total: 481ms	remaining: 859ms
359:	learn: 0.3200326	total: 482ms	remaining: 858ms
360:	learn: 0.3199526	total: 484ms	remaining: 856ms
361:	learn: 0.3198354	total: 485ms	remaining: 855ms
362:	learn: 0.3197602	total: 486ms	remaining: 854ms
363:	learn: 0.3196186	total: 488ms	remaining: 852ms
364:	learn: 0.3194431	total: 489ms	remaining: 851ms
365:	learn: 0.3192660	total: 490ms	remaining: 849ms
366:	learn: 0.3191288	total: 491ms	remaining: 847ms
367:	learn: 0.3190495	total: 492ms	remaining: 846ms
368:	learn: 0.3188513	total: 493ms	remaining: 844ms
369:	learn: 0.3187549	total: 494ms	remaining: 842ms
370:	learn: 0.3185622	total: 496ms	remaining: 840ms
371:	learn: 0.3185491	total: 496ms	remaining: 838ms
372:	learn: 0.3184619	total: 497ms	remaining: 836ms
373:	learn: 0.3183153	total: 499ms	remaining: 834ms
374:	learn: 0.3182299	total: 500ms	remaining: 833ms
375:	learn: 0.3180588	total: 501ms	remaining: 832ms
376:	learn: 0.3179455	total: 503ms	remaining: 831ms
377:	learn: 0.3177902	total: 504ms	remaining: 829ms
378:	learn: 0.3176545	total: 506ms	remaining: 829ms
379:	learn: 0.3175910	total: 507ms	remaining: 827ms
380:	learn: 0.3172902	total: 508ms	remaining: 826ms
381:	learn: 0.3171671	total: 509ms	remaining: 824ms
382:	learn: 0.3171075	total: 510ms	remaining: 822ms
383:	learn: 0.3169468	total: 511ms	remaining: 820ms
384:	learn: 0.3167428	total: 512ms	remaining: 819ms

   TRAIN_acc_MEAN  TRAIN_acc_STD  VAL_acc_MEAN  VAL_acc_STD   OOF_acc
0        0.927023       0.005692      0.846245     0.031439  0.855219

In [35]:
make_submit(
    base, preprocessor, X_train, y_train, df_submit, "cb_no_tune_final_features.csv"
)

Файл успешно сохранен: d:\vs_projects\fp_titanic\data\external\cb_no_tune_final_features.csv

### tuning lgbm

In [52]:
import optuna
from optuna.samplers import TPESampler

In [53]:
def objective_lgbm(trial):
    params = {
        "random_state": gseed,
        "n_estimators": trial.suggest_int("n_estimators", 100, 1000),
        "max_depth": trial.suggest_int("max_depth", 3, 10),
        "num_leaves": trial.suggest_int("num_leaves", 15, 255),
        "learning_rate": trial.suggest_float("learning_rate", 0.005, 0.3, log=True),
        "min_child_samples": trial.suggest_int("min_child_samples", 5, 100),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 10.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 10.0, log=True),
    }

    model = LGBMClassifier(**params, verbosity=-1)
    _, _, metrics = cv_result(model, X_train, y_train, rskf, preprocessor)

    return metrics["OOF_acc"].item()

In [55]:
study_lgbm = optuna.create_study(direction="maximize", sampler=TPESampler(seed=gseed))
study_lgbm.optimize(objective_lgbm, n_trials=100, show_progress_bar=True)

[I 2026-09-05 19:28:44,267] A new study created in memory with name: no-name-8d0f0b76-e653-4381-baf8-5949ee5153b4

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-09-05 19:28:49,353] Trial 0 finished with value: 0.8462401795735129 and parameters: {'n_estimators': 565, 'max_depth': 7, 'num_leaves': 21, 'learning_rate': 0.010091633082984282, 'min_child_samples': 70, 'subsample': 0.9169484313180383, 'colsample_bytree': 0.6534831098361189, 'reg_alpha': 1.1028532241013205, 'reg_lambda': 0.03118133864355715}. Best is trial 0 with value: 0.8462401795735129.
[I 2026-09-05 19:28:53,396] Trial 1 finished with value: 0.8451178451178452 and parameters: {'n_estimators': 271, 'max_depth': 7, 'num_leaves': 99, 'learning_rate': 0.010529365650093677, 'min_child_samples': 80, 'subsample': 0.9827416112059846, 'colsample_bytree': 0.6161768309073803, 'reg_alpha': 5.650057960050972e-08, 'reg_lambda': 0.0027035586822681547}. Best is trial 0 with value: 0.8462401795735129.
[I 2026-09-05 19:28:58,154] Trial 2 finished with value: 0.8406285072951739 and parameters: {'n_estimators': 756, 'max_depth': 5, 'num_leaves': 180, 'learning_rate': 0.041669347616674714, 'min_child_samples': 9, 'subsample': 0.5689346187810531, 'colsample_bytree': 0.5934837130689605, 'reg_alpha': 8.889167922254462, 'reg_lambda': 0.0004852757284257302}. Best is trial 0 with value: 0.8462401795735129.
[I 2026-09-05 19:29:03,107] Trial 3 finished with value: 0.8451178451178452 and parameters: {'n_estimators': 621, 'max_depth': 8, 'num_leaves': 145, 'learning_rate': 0.2102302199638932, 'min_child_samples': 82, 'subsample': 0.7014989153468937, 'colsample_bytree': 0.6786121714103939, 'reg_alpha': 3.7660877284938508, 'reg_lambda': 1.237896118074375e-05}. Best is trial 0 with value: 0.8462401795735129.
[I 2026-09-05 19:29:08,448] Trial 4 finished with value: 0.8428731762065096 and parameters: {'n_estimators': 879, 'max_depth': 9, 'num_leaves': 144, 'learning_rate': 0.21840374077640223, 'min_child_samples': 14, 'subsample': 0.5514237465803747, 'colsample_bytree': 0.8507536478479129, 'reg_alpha': 1.033519849907543, 'reg_lambda': 2.7292461609423586e-07}. Best is trial 0 with value: 0.8462401795735129.
[I 2026-09-05 19:29:15,571] Trial 5 finished with value: 0.8406285072951739 and parameters: {'n_estimators': 348, 'max_depth': 8, 'num_leaves': 54, 'learning_rate': 0.08833116693109885, 'min_child_samples': 51, 'subsample': 0.8403388840881794, 'colsample_bytree': 0.7607740961629297, 'reg_alpha': 2.4579341856167136e-08, 'reg_lambda': 1.0361662241687912e-06}. Best is trial 0 with value: 0.8462401795735129.
[I 2026-09-05 19:29:26,562] Trial 6 finished with value: 0.8473625140291807 and parameters: {'n_estimators': 618, 'max_depth': 3, 'num_leaves': 135, 'learning_rate': 0.008797755549584804, 'min_child_samples': 10, 'subsample': 0.5891384612680759, 'colsample_bytree': 0.7211840657563724, 'reg_alpha': 0.7911993497243279, 'reg_lambda': 3.4944365633452965}. Best is trial 6 with value: 0.8473625140291807.
[I 2026-09-05 19:29:35,818] Trial 7 finished with value: 0.8484848484848485 and parameters: {'n_estimators': 530, 'max_depth': 6, 'num_leaves': 168, 'learning_rate': 0.018887397439322946, 'min_child_samples': 16, 'subsample': 0.5255504981978874, 'colsample_bytree': 0.8188293264089126, 'reg_alpha': 0.20435866371403186, 'reg_lambda': 0.010773176696694801}. Best is trial 7 with value: 0.8484848484848485.
[I 2026-09-05 19:29:44,103] Trial 8 finished with value: 0.8473625140291807 and parameters: {'n_estimators': 687, 'max_depth': 6, 'num_leaves': 173, 'learning_rate': 0.011773098703191275, 'min_child_samples': 68, 'subsample': 0.7648116993765073, 'colsample_bytree': 0.8742601849252463, 'reg_alpha': 6.979297368822564e-08, 'reg_lambda': 0.11499968474000738}. Best is trial 7 with value: 0.8484848484848485.
[I 2026-09-05 19:29:57,578] Trial 9 finished with value: 0.8103254769921436 and parameters: {'n_estimators': 719, 'max_depth': 8, 'num_leaves': 134, 'learning_rate': 0.2712124437667118, 'min_child_samples': 24, 'subsample': 0.6495102048264059, 'colsample_bytree': 0.6138279463970966, 'reg_alpha': 2.7134384139169515e-08, 'reg_lambda': 1.3669172276235095}. Best is trial 7 with value: 0.8484848484848485.
[I 2026-09-05 19:30:17,234] Trial 10 finished with value: 0.8361391694725028 and parameters: {'n_estimators': 995, 'max_depth': 10, 'num_leaves': 252, 'learning_rate': 0.0268806793267163, 'min_child_samples': 38, 'subsample': 0.5054198636453676, 'colsample_bytree': 0.99916674525379, 'reg_alpha': 0.0013869867207921868, 'reg_lambda': 1.0100110231027923e-08}. Best is trial 7 with value: 0.8484848484848485.
[I 2026-09-05 19:30:25,433] Trial 11 finished with value: 0.8428731762065096 and parameters: {'n_estimators': 455, 'max_depth': 3, 'num_leaves': 230, 'learning_rate': 0.006088847797337794, 'min_child_samples': 31, 'subsample': 0.6192748374038921, 'colsample_bytree': 0.7449676177534647, 'reg_alpha': 0.016129237792073335, 'reg_lambda': 9.986420405817173}. Best is trial 7 with value: 0.8484848484848485.
[I 2026-09-05 19:30:30,680] Trial 12 finished with value: 0.8417508417508418 and parameters: {'n_estimators': 118, 'max_depth': 3, 'num_leaves': 198, 'learning_rate': 0.0189759432917635, 'min_child_samples': 7, 'subsample': 0.5024830551944229, 'colsample_bytree': 0.8282893190679294, 'reg_alpha': 0.01014577979910352, 'reg_lambda': 0.1245268601421057}. Best is trial 7 with value: 0.8484848484848485.
[I 2026-09-05 19:30:36,348] Trial 13 finished with value: 0.8451178451178452 and parameters: {'n_estimators': 488, 'max_depth': 4, 'num_leaves': 94, 'learning_rate': 0.00572125215198942, 'min_child_samples': 42, 'subsample': 0.6386385541047213, 'colsample_bytree': 0.940647219407328, 'reg_alpha': 0.00025635405651556597, 'reg_lambda': 0.00030749744266564763}. Best is trial 7 with value: 0.8484848484848485.
[I 2026-09-05 19:30:43,129] Trial 14 finished with value: 0.8574635241301908 and parameters: {'n_estimators': 409, 'max_depth': 5, 'num_leaves': 104, 'learning_rate': 0.04755571719306031, 'min_child_samples': 21, 'subsample': 0.7279664239579899, 'colsample_bytree': 0.5322640057787851, 'reg_alpha': 0.1057163625351844, 'reg_lambda': 4.628797701922884}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:30:49,638] Trial 15 finished with value: 0.8507295173961841 and parameters: {'n_estimators': 330, 'max_depth': 5, 'num_leaves': 93, 'learning_rate': 0.05547052735239082, 'min_child_samples': 23, 'subsample': 0.7595719371320842, 'colsample_bytree': 0.5465561165457505, 'reg_alpha': 0.053847955332011053, 'reg_lambda': 0.013148450526370174}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:30:54,304] Trial 16 finished with value: 0.8473625140291807 and parameters: {'n_estimators': 268, 'max_depth': 5, 'num_leaves': 92, 'learning_rate': 0.07523232783863823, 'min_child_samples': 50, 'subsample': 0.7605935849037253, 'colsample_bytree': 0.5010863110206033, 'reg_alpha': 2.0380373649497974e-05, 'reg_lambda': 0.5030838035268138}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:30:59,630] Trial 17 finished with value: 0.8417508417508418 and parameters: {'n_estimators': 383, 'max_depth': 5, 'num_leaves': 61, 'learning_rate': 0.06909841322727608, 'min_child_samples': 97, 'subsample': 0.8103970734098732, 'colsample_bytree': 0.5026277936728338, 'reg_alpha': 0.04328581960178335, 'reg_lambda': 6.965600220394459e-05}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:31:02,954] Trial 18 finished with value: 0.8484848484848485 and parameters: {'n_estimators': 103, 'max_depth': 4, 'num_leaves': 55, 'learning_rate': 0.11509423399010997, 'min_child_samples': 23, 'subsample': 0.7162581106670052, 'colsample_bytree': 0.5481091349121707, 'reg_alpha': 2.0602608365615707e-05, 'reg_lambda': 0.0025863954457723895}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:31:08,985] Trial 19 finished with value: 0.8529741863075196 and parameters: {'n_estimators': 201, 'max_depth': 6, 'num_leaves': 118, 'learning_rate': 0.04169449172009719, 'min_child_samples': 26, 'subsample': 0.8654907385703454, 'colsample_bytree': 0.5458720251739129, 'reg_alpha': 0.0007943727511715306, 'reg_lambda': 0.5692024002319312}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:31:13,898] Trial 20 finished with value: 0.8439955106621774 and parameters: {'n_estimators': 189, 'max_depth': 6, 'num_leaves': 123, 'learning_rate': 0.0338169673427057, 'min_child_samples': 51, 'subsample': 0.8913145519639553, 'colsample_bytree': 0.5594290945694075, 'reg_alpha': 0.0006923123654252389, 'reg_lambda': 0.3235852709300714}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:31:21,897] Trial 21 finished with value: 0.8507295173961841 and parameters: {'n_estimators': 341, 'max_depth': 4, 'num_leaves': 109, 'learning_rate': 0.05009819135547845, 'min_child_samples': 29, 'subsample': 0.8205444851693302, 'colsample_bytree': 0.5582257713991174, 'reg_alpha': 0.07611065141847133, 'reg_lambda': 0.023338411892213258}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:31:36,841] Trial 22 finished with value: 0.8462401795735129 and parameters: {'n_estimators': 245, 'max_depth': 5, 'num_leaves': 88, 'learning_rate': 0.11390013723326975, 'min_child_samples': 37, 'subsample': 0.8842608852810986, 'colsample_bytree': 0.5363219288585143, 'reg_alpha': 0.004034737431074418, 'reg_lambda': 1.9412507550539562}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:31:45,461] Trial 23 finished with value: 0.8451178451178452 and parameters: {'n_estimators': 401, 'max_depth': 7, 'num_leaves': 74, 'learning_rate': 0.05176547170919124, 'min_child_samples': 19, 'subsample': 0.6928456583143128, 'colsample_bytree': 0.6625524053142362, 'reg_alpha': 8.028103608567174e-05, 'reg_lambda': 6.101442760626045}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:31:49,670] Trial 24 finished with value: 0.8484848484848485 and parameters: {'n_estimators': 181, 'max_depth': 6, 'num_leaves': 32, 'learning_rate': 0.025221987313050174, 'min_child_samples': 30, 'subsample': 0.7724264510108748, 'colsample_bytree': 0.5877592409939718, 'reg_alpha': 0.17355160815871334, 'reg_lambda': 0.1433842606545136}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:31:53,814] Trial 25 finished with value: 0.8484848484848485 and parameters: {'n_estimators': 306, 'max_depth': 4, 'num_leaves': 116, 'learning_rate': 0.12833209860736536, 'min_child_samples': 44, 'subsample': 0.9621173426097109, 'colsample_bytree': 0.5270393918307339, 'reg_alpha': 9.323134012563754e-07, 'reg_lambda': 0.7574545781189302}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:31:59,119] Trial 26 finished with value: 0.8484848484848485 and parameters: {'n_estimators': 442, 'max_depth': 5, 'num_leaves': 76, 'learning_rate': 0.05881144125645976, 'min_child_samples': 23, 'subsample': 0.7350121438048605, 'colsample_bytree': 0.6335420003320944, 'reg_alpha': 0.0030240357795796526, 'reg_lambda': 0.005473845511723963}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:32:03,030] Trial 27 finished with value: 0.8462401795735129 and parameters: {'n_estimators': 194, 'max_depth': 6, 'num_leaves': 157, 'learning_rate': 0.03392441266463389, 'min_child_samples': 35, 'subsample': 0.7977626778210359, 'colsample_bytree': 0.5835874011858668, 'reg_alpha': 0.019757466621829454, 'reg_lambda': 0.03235849334894298}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:32:09,131] Trial 28 finished with value: 0.8395061728395061 and parameters: {'n_estimators': 392, 'max_depth': 7, 'num_leaves': 116, 'learning_rate': 0.03710407948172164, 'min_child_samples': 17, 'subsample': 0.8416154370766037, 'colsample_bytree': 0.6925235621530677, 'reg_alpha': 0.0002684157075936934, 'reg_lambda': 0.0010705788867513629}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:32:14,615] Trial 29 finished with value: 0.8439955106621774 and parameters: {'n_estimators': 537, 'max_depth': 7, 'num_leaves': 16, 'learning_rate': 0.017013960005627247, 'min_child_samples': 65, 'subsample': 0.9464214716129398, 'colsample_bytree': 0.6328135155185499, 'reg_alpha': 0.420242373822403, 'reg_lambda': 0.04332112214262293}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:32:18,601] Trial 30 finished with value: 0.8462401795735129 and parameters: {'n_estimators': 219, 'max_depth': 4, 'num_leaves': 39, 'learning_rate': 0.0906889278719174, 'min_child_samples': 5, 'subsample': 0.8835640196940693, 'colsample_bytree': 0.5793771058636624, 'reg_alpha': 0.07550077466346067, 'reg_lambda': 0.38213392933864065}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:32:22,885] Trial 31 finished with value: 0.8439955106621774 and parameters: {'n_estimators': 320, 'max_depth': 4, 'num_leaves': 108, 'learning_rate': 0.04989805208343968, 'min_child_samples': 28, 'subsample': 0.838547438423718, 'colsample_bytree': 0.5538511192347663, 'reg_alpha': 1.9021396789943366, 'reg_lambda': 0.010802129078732955}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:32:27,688] Trial 32 finished with value: 0.8496071829405163 and parameters: {'n_estimators': 329, 'max_depth': 5, 'num_leaves': 105, 'learning_rate': 0.026334579665289716, 'min_child_samples': 29, 'subsample': 0.8032914033522683, 'colsample_bytree': 0.519787926195488, 'reg_alpha': 0.06750535301911478, 'reg_lambda': 0.022844581452905986}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:32:31,905] Trial 33 finished with value: 0.8507295173961841 and parameters: {'n_estimators': 279, 'max_depth': 4, 'num_leaves': 82, 'learning_rate': 0.045941425722529385, 'min_child_samples': 22, 'subsample': 0.6751566677426069, 'colsample_bytree': 0.6094507907473068, 'reg_alpha': 0.006383472841901688, 'reg_lambda': 0.06083017110726696}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:32:35,802] Trial 34 finished with value: 0.8417508417508418 and parameters: {'n_estimators': 448, 'max_depth': 5, 'num_leaves': 126, 'learning_rate': 0.06330214258708765, 'min_child_samples': 12, 'subsample': 0.7462245549795081, 'colsample_bytree': 0.5667136513142518, 'reg_alpha': 7.721874443342828, 'reg_lambda': 1.9668375892566612}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:32:39,385] Trial 35 finished with value: 0.8417508417508418 and parameters: {'n_estimators': 143, 'max_depth': 6, 'num_leaves': 104, 'learning_rate': 0.039846173935782735, 'min_child_samples': 43, 'subsample': 0.9203502176197881, 'colsample_bytree': 0.6471513582621586, 'reg_alpha': 0.21473750828520005, 'reg_lambda': 0.00017105529046299985}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:32:44,423] Trial 36 finished with value: 0.8462401795735129 and parameters: {'n_estimators': 364, 'max_depth': 5, 'num_leaves': 67, 'learning_rate': 0.0842606178910252, 'min_child_samples': 33, 'subsample': 0.8620838696921028, 'colsample_bytree': 0.5298713752701646, 'reg_alpha': 0.023851340184669483, 'reg_lambda': 0.0015313617765070964}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:32:48,566] Trial 37 finished with value: 0.8439955106621774 and parameters: {'n_estimators': 596, 'max_depth': 3, 'num_leaves': 147, 'learning_rate': 0.14301402256635604, 'min_child_samples': 60, 'subsample': 0.7876388061254146, 'colsample_bytree': 0.6096003233916317, 'reg_alpha': 1.682448839537313, 'reg_lambda': 0.19427854766906608}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:32:52,593] Trial 38 finished with value: 0.8540965207631874 and parameters: {'n_estimators': 247, 'max_depth': 4, 'num_leaves': 202, 'learning_rate': 0.05595218955413295, 'min_child_samples': 26, 'subsample': 0.9925770096822089, 'colsample_bytree': 0.5650300273092647, 'reg_alpha': 3.4124167980422224e-06, 'reg_lambda': 1.4574162033141875e-05}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:32:58,120] Trial 39 finished with value: 0.8518518518518519 and parameters: {'n_estimators': 243, 'max_depth': 7, 'num_leaves': 194, 'learning_rate': 0.030608551636462655, 'min_child_samples': 12, 'subsample': 0.9877650411261885, 'colsample_bytree': 0.6909491486391617, 'reg_alpha': 1.092654775333665e-06, 'reg_lambda': 7.466724833117895e-06}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:33:03,406] Trial 40 finished with value: 0.8406285072951739 and parameters: {'n_estimators': 157, 'max_depth': 8, 'num_leaves': 195, 'learning_rate': 0.01288850022692582, 'min_child_samples': 11, 'subsample': 0.9946181390736905, 'colsample_bytree': 0.7088244265436736, 'reg_alpha': 8.06226867659947e-07, 'reg_lambda': 3.867072912785187e-06}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:33:08,497] Trial 41 finished with value: 0.8484848484848485 and parameters: {'n_estimators': 234, 'max_depth': 7, 'num_leaves': 217, 'learning_rate': 0.029790935860065326, 'min_child_samples': 16, 'subsample': 0.9669198837688258, 'colsample_bytree': 0.774393069602693, 'reg_alpha': 1.6446284597051739e-06, 'reg_lambda': 3.084672604128756e-05}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:33:13,424] Trial 42 finished with value: 0.8518518518518519 and parameters: {'n_estimators': 285, 'max_depth': 6, 'num_leaves': 186, 'learning_rate': 0.023450901827945396, 'min_child_samples': 25, 'subsample': 0.9335820748463479, 'colsample_bytree': 0.6685787399572773, 'reg_alpha': 2.8051796759172498e-06, 'reg_lambda': 4.0967238061503183e-07}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:33:19,426] Trial 43 finished with value: 0.8529741863075196 and parameters: {'n_estimators': 275, 'max_depth': 9, 'num_leaves': 193, 'learning_rate': 0.020795138841130583, 'min_child_samples': 19, 'subsample': 0.9312761721984593, 'colsample_bytree': 0.6679726217953805, 'reg_alpha': 3.749225903865903e-06, 'reg_lambda': 2.1117997119409685e-07}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:33:26,029] Trial 44 finished with value: 0.8473625140291807 and parameters: {'n_estimators': 229, 'max_depth': 9, 'num_leaves': 218, 'learning_rate': 0.015602813114356332, 'min_child_samples': 13, 'subsample': 0.998467336001458, 'colsample_bytree': 0.7321595622983167, 'reg_alpha': 8.49229652970026e-08, 'reg_lambda': 3.5936741503373244e-08}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:33:39,133] Trial 45 finished with value: 0.8540965207631874 and parameters: {'n_estimators': 836, 'max_depth': 10, 'num_leaves': 254, 'learning_rate': 0.009467239540250437, 'min_child_samples': 19, 'subsample': 0.970788860971871, 'colsample_bytree': 0.6843449615118545, 'reg_alpha': 1.991349804601211e-07, 'reg_lambda': 3.7732063248085004e-06}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:33:52,795] Trial 46 finished with value: 0.8484848484848485 and parameters: {'n_estimators': 831, 'max_depth': 10, 'num_leaves': 251, 'learning_rate': 0.009592441334046974, 'min_child_samples': 18, 'subsample': 0.9072068122785066, 'colsample_bytree': 0.6350505577253056, 'reg_alpha': 2.1139627962085366e-07, 'reg_lambda': 8.979149637790401e-08}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:34:04,256] Trial 47 finished with value: 0.8462401795735129 and parameters: {'n_estimators': 667, 'max_depth': 9, 'num_leaves': 237, 'learning_rate': 0.006485390586741189, 'min_child_samples': 20, 'subsample': 0.9523909147807729, 'colsample_bytree': 0.7746065766267229, 'reg_alpha': 5.809514218839869e-06, 'reg_lambda': 1.4966687084390534e-06}. Best is trial 14 with value: 0.8574635241301908.
[I 2026-09-05 19:34:16,628] Trial 48 finished with value: 0.8451178451178452 and parameters: {'n_estimators': 937, 'max_depth': 10, 'num_leaves': 209, 'learning_rate': 0.021284187459987565, 'min_child_samples': 27, 'subsample': 0.9729680975113005, 'colsample_bytree': 0.601896262244794, 'reg_alpha': 2.6361364519814436e-07, 'reg_lambda': 2.873794296907003e-07}. Best is trial 14 with value: 0.8574635241301908.

In [56]:
print(study_lgbm.best_params)
print(study_lgbm.best_value)

{'n_estimators': 409, 'max_depth': 5, 'num_leaves': 104, 'learning_rate': 0.04755571719306031, 'min_child_samples': 21, 'subsample': 0.7279664239579899, 'colsample_bytree': 0.5322640057787851, 'reg_alpha': 0.1057163625351844, 'reg_lambda': 4.628797701922884}
0.8574635241301908

In [60]:
best_lgbm = LGBMClassifier(**study_lgbm.best_params, random_state=gseed, verbosity=-1)
_, _, metrics = cv_result(best_lgbm, X_train, y_train, rskf, preprocessor)
metrics

   TRAIN_acc_MEAN  TRAIN_acc_STD  VAL_acc_MEAN  VAL_acc_STD   OOF_acc
0        0.927722       0.006749      0.848931     0.034657  0.857464

In [61]:
make_submit(
    best_lgbm, preprocessor, X_train, y_train, df_submit, "best_lgbm_final_features.csv"
)

Файл успешно сохранен: d:\vs_projects\fp_titanic\data\external\best_lgbm_final_features.csv

### tuning catboost

In [57]:
def objective_catboost(trial):
    params = {
        "random_state": gseed,
        "iterations": trial.suggest_int("iterations", 200, 1500),
        "depth": trial.suggest_int("depth", 3, 10),
        "learning_rate": trial.suggest_float("learning_rate", 0.005, 0.3, log=True),
        "l2_leaf_reg": trial.suggest_float("l2_leaf_reg", 1.0, 10.0, log=True),
        "bagging_temperature": trial.suggest_float("bagging_temperature", 0.0, 10.0),
        "border_count": trial.suggest_int("border_count", 32, 255),
        "verbose": False,
    }

    model = CatBoostClassifier(**params)

    _, _, metrics = cv_result(model, X_train, y_train, rskf, preprocessor)

    return metrics["OOF_acc"].item()

In [58]:
study_cb = optuna.create_study(direction="maximize", sampler=TPESampler(seed=gseed))
study_cb.optimize(objective_catboost, n_trials=100, show_progress_bar=True)

[I 2026-09-05 19:39:50,108] A new study created in memory with name: no-name-a37fa381-51b2-4dc6-a67f-7461cf906204

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-09-05 19:41:11,245] Trial 0 finished with value: 0.8540965207631874 and parameters: {'iterations': 871, 'depth': 7, 'learning_rate': 0.0056182555017538546, 'l2_leaf_reg': 1.4842998932803027, 'bagging_temperature': 6.852769816973126, 'border_count': 218}. Best is trial 0 with value: 0.8540965207631874.
[I 2026-09-05 19:43:48,603] Trial 1 finished with value: 0.8383838383838383 and parameters: {'iterations': 599, 'depth': 10, 'learning_rate': 0.09593655612243439, 'l2_leaf_reg': 1.5485989276883412, 'bagging_temperature': 5.542275911247872, 'border_count': 110}. Best is trial 0 with value: 0.8540965207631874.
[I 2026-09-05 19:45:15,901] Trial 2 finished with value: 0.8249158249158249 and parameters: {'iterations': 436, 'depth': 9, 'learning_rate': 0.2604624992542696, 'l2_leaf_reg': 1.7074722798750672, 'bagging_temperature': 0.8356143366334368, 'border_count': 167}. Best is trial 0 with value: 0.8540965207631874.
[I 2026-09-05 19:46:26,146] Trial 3 finished with value: 0.8226711560044894 and parameters: {'iterations': 1148, 'depth': 5, 'learning_rate': 0.08270815057775043, 'l2_leaf_reg': 3.2950914647958833, 'bagging_temperature': 0.48484537426400576, 'border_count': 62}. Best is trial 0 with value: 0.8540965207631874.
[I 2026-09-05 19:48:53,187] Trial 4 finished with value: 0.8451178451178452 and parameters: {'iterations': 443, 'depth': 10, 'learning_rate': 0.042149442091141257, 'l2_leaf_reg': 3.791312087330114, 'bagging_temperature': 7.348190582693819, 'border_count': 153}. Best is trial 0 with value: 0.8540965207631874.
[I 2026-09-05 19:52:31,329] Trial 5 finished with value: 0.8338945005611672 and parameters: {'iterations': 1388, 'depth': 9, 'learning_rate': 0.026035210949641265, 'l2_leaf_reg': 2.27627297789018, 'bagging_temperature': 9.528767147108733, 'border_count': 108}. Best is trial 0 with value: 0.8540965207631874.
[I 2026-09-05 19:55:12,301] Trial 6 finished with value: 0.8271604938271605 and parameters: {'iterations': 1325, 'depth': 9, 'learning_rate': 0.045279587132660434, 'l2_leaf_reg': 8.365066013311049, 'bagging_temperature': 0.9714647976501556, 'border_count': 55}. Best is trial 0 with value: 0.8540965207631874.
[I 2026-09-05 19:59:37,788] Trial 7 finished with value: 0.8473625140291807 and parameters: {'iterations': 1112, 'depth': 10, 'learning_rate': 0.009609313291831697, 'l2_leaf_reg': 1.8861340045076325, 'bagging_temperature': 6.724915296568056, 'border_count': 68}. Best is trial 0 with value: 0.8540965207631874.
[I 2026-09-05 20:01:01,924] Trial 8 finished with value: 0.8361391694725028 and parameters: {'iterations': 1112, 'depth': 6, 'learning_rate': 0.08115551329364151, 'l2_leaf_reg': 3.323136589920605, 'bagging_temperature': 0.4339669443408434, 'border_count': 82}. Best is trial 0 with value: 0.8540965207631874.
[I 2026-09-05 20:01:57,886] Trial 9 finished with value: 0.8428731762065096 and parameters: {'iterations': 948, 'depth': 3, 'learning_rate': 0.03874834557544829, 'l2_leaf_reg': 1.37407224786821, 'bagging_temperature': 0.5280840108926621, 'border_count': 71}. Best is trial 0 with value: 0.8540965207631874.
[I 2026-09-05 20:03:18,661] Trial 10 finished with value: 0.8507295173961841 and parameters: {'iterations': 729, 'depth': 7, 'learning_rate': 0.00554325144761852, 'l2_leaf_reg': 1.0029803709329739, 'bagging_temperature': 3.6207837142183457, 'border_count': 231}. Best is trial 0 with value: 0.8540965207631874.
[I 2026-09-05 20:04:43,363] Trial 11 finished with value: 0.8484848484848485 and parameters: {'iterations': 763, 'depth': 7, 'learning_rate': 0.005003078847702978, 'l2_leaf_reg': 1.0299252684062523, 'bagging_temperature': 3.767221432116356, 'border_count': 251}. Best is trial 0 with value: 0.8540965207631874.
[I 2026-09-05 20:06:09,967] Trial 12 finished with value: 0.8518518518518519 and parameters: {'iterations': 780, 'depth': 7, 'learning_rate': 0.0058708667956275055, 'l2_leaf_reg': 1.0170456337176579, 'bagging_temperature': 3.389804341617382, 'border_count': 244}. Best is trial 0 with value: 0.8540965207631874.
[I 2026-09-05 20:06:37,734] Trial 13 finished with value: 0.8473625140291807 and parameters: {'iterations': 227, 'depth': 7, 'learning_rate': 0.010654798209674217, 'l2_leaf_reg': 1.1927427995227873, 'bagging_temperature': 3.5578428109328097, 'border_count': 208}. Best is trial 0 with value: 0.8540965207631874.
[I 2026-09-05 20:07:46,739] Trial 14 finished with value: 0.8496071829405163 and parameters: {'iterations': 918, 'depth': 5, 'learning_rate': 0.011939171228432232, 'l2_leaf_reg': 2.3724892717170074, 'bagging_temperature': 9.26564445800547, 'border_count': 195}. Best is trial 0 with value: 0.8540965207631874.
[I 2026-09-05 20:10:03,905] Trial 15 finished with value: 0.8496071829405163 and parameters: {'iterations': 891, 'depth': 8, 'learning_rate': 0.01634640193058362, 'l2_leaf_reg': 7.608419304487845, 'bagging_temperature': 5.067652646942811, 'border_count': 249}. Best is trial 0 with value: 0.8540965207631874.
[I 2026-09-05 20:10:50,082] Trial 16 finished with value: 0.8439955106621774 and parameters: {'iterations': 625, 'depth': 5, 'learning_rate': 0.007581967812390585, 'l2_leaf_reg': 1.347216119364185, 'bagging_temperature': 2.341670032406758, 'border_count': 205}. Best is trial 0 with value: 0.8540965207631874.
[I 2026-09-05 20:11:33,468] Trial 17 finished with value: 0.8473625140291807 and parameters: {'iterations': 793, 'depth': 3, 'learning_rate': 0.017426511806459728, 'l2_leaf_reg': 2.193234769406574, 'bagging_temperature': 7.944138119381916, 'border_count': 177}. Best is trial 0 with value: 0.8540965207631874.
[I 2026-09-05 20:12:21,179] Trial 18 finished with value: 0.8451178451178452 and parameters: {'iterations': 512, 'depth': 6, 'learning_rate': 0.006823735274001615, 'l2_leaf_reg': 4.956146441920621, 'bagging_temperature': 5.57874951394602, 'border_count': 225}. Best is trial 0 with value: 0.8540965207631874.
[I 2026-09-05 20:14:24,614] Trial 19 finished with value: 0.8428731762065096 and parameters: {'iterations': 1018, 'depth': 8, 'learning_rate': 0.018812661955075485, 'l2_leaf_reg': 1.1909732837353546, 'bagging_temperature': 2.291301169979982, 'border_count': 137}. Best is trial 0 with value: 0.8540965207631874.
[I 2026-09-05 20:14:47,795] Trial 20 finished with value: 0.8417508417508418 and parameters: {'iterations': 232, 'depth': 6, 'learning_rate': 0.008074580797158486, 'l2_leaf_reg': 1.8966963485456108, 'bagging_temperature': 8.200241863028467, 'border_count': 226}. Best is trial 0 with value: 0.8540965207631874.
[I 2026-09-05 20:16:08,103] Trial 21 finished with value: 0.8518518518518519 and parameters: {'iterations': 753, 'depth': 7, 'learning_rate': 0.0052067521683363165, 'l2_leaf_reg': 1.017994728146553, 'bagging_temperature': 4.50614792294353, 'border_count': 233}. Best is trial 0 with value: 0.8540965207631874.
[I 2026-09-05 20:17:54,492] Trial 22 finished with value: 0.856341189674523 and parameters: {'iterations': 816, 'depth': 8, 'learning_rate': 0.005001699460835567, 'l2_leaf_reg': 1.0101827774698053, 'bagging_temperature': 4.4167144250519215, 'border_count': 190}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 20:19:51,407] Trial 23 finished with value: 0.8473625140291807 and parameters: {'iterations': 856, 'depth': 8, 'learning_rate': 0.012710778926024019, 'l2_leaf_reg': 1.506379541548391, 'bagging_temperature': 6.327183562781753, 'border_count': 194}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 20:21:13,944] Trial 24 finished with value: 0.8518518518518519 and parameters: {'iterations': 649, 'depth': 8, 'learning_rate': 0.007177147515899003, 'l2_leaf_reg': 1.2352192475470225, 'bagging_temperature': 2.6035287206364424, 'border_count': 178}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 20:22:39,284] Trial 25 finished with value: 0.8507295173961841 and parameters: {'iterations': 1015, 'depth': 6, 'learning_rate': 0.005044584846434045, 'l2_leaf_reg': 1.5784442223327873, 'bagging_temperature': 4.716320977368165, 'border_count': 213}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 20:24:26,093] Trial 26 finished with value: 0.8518518518518519 and parameters: {'iterations': 1000, 'depth': 7, 'learning_rate': 0.007839026954225841, 'l2_leaf_reg': 1.1885115470052654, 'bagging_temperature': 1.6616855806002757, 'border_count': 253}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 20:26:17,836] Trial 27 finished with value: 0.8507295173961841 and parameters: {'iterations': 834, 'depth': 8, 'learning_rate': 0.012940317135028178, 'l2_leaf_reg': 2.725350860915944, 'bagging_temperature': 6.329113662861195, 'border_count': 188}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 20:26:52,453] Trial 28 finished with value: 0.8439955106621774 and parameters: {'iterations': 535, 'depth': 4, 'learning_rate': 0.009389516061536802, 'l2_leaf_reg': 1.8407760721283164, 'bagging_temperature': 3.091977428629029, 'border_count': 154}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 20:29:56,331] Trial 29 finished with value: 0.8473625140291807 and parameters: {'iterations': 1194, 'depth': 9, 'learning_rate': 0.006588614950582657, 'l2_leaf_reg': 1.4447611932699143, 'bagging_temperature': 5.770026684044257, 'border_count': 119}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 20:31:11,263] Trial 30 finished with value: 0.8428731762065096 and parameters: {'iterations': 686, 'depth': 7, 'learning_rate': 0.024768893519764086, 'l2_leaf_reg': 1.575650371951992, 'bagging_temperature': 4.27382128007775, 'border_count': 216}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 20:32:31,307] Trial 31 finished with value: 0.8529741863075196 and parameters: {'iterations': 730, 'depth': 7, 'learning_rate': 0.005997333448999672, 'l2_leaf_reg': 1.0631361106740367, 'bagging_temperature': 4.147313743348013, 'border_count': 236}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 20:33:24,398] Trial 32 finished with value: 0.8451178451178452 and parameters: {'iterations': 576, 'depth': 6, 'learning_rate': 0.006272478996468308, 'l2_leaf_reg': 1.1175923462541575, 'bagging_temperature': 4.150771395540659, 'border_count': 240}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 20:34:23,948] Trial 33 finished with value: 0.8249158249158249 and parameters: {'iterations': 366, 'depth': 8, 'learning_rate': 0.21998803754516502, 'l2_leaf_reg': 1.2918336954466916, 'bagging_temperature': 5.2119010243823665, 'border_count': 218}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 20:35:16,364] Trial 34 finished with value: 0.8507295173961841 and parameters: {'iterations': 693, 'depth': 7, 'learning_rate': 0.00914135629177817, 'l2_leaf_reg': 1.1148790893254126, 'bagging_temperature': 2.999706047239929, 'border_count': 36}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 20:37:58,101] Trial 35 finished with value: 0.8529741863075196 and parameters: {'iterations': 811, 'depth': 9, 'learning_rate': 0.006552536918138287, 'l2_leaf_reg': 1.717853267703849, 'bagging_temperature': 7.101136175081575, 'border_count': 241}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 20:40:52,272] Trial 36 finished with value: 0.8462401795735129 and parameters: {'iterations': 948, 'depth': 9, 'learning_rate': 0.012695966055168834, 'l2_leaf_reg': 1.7299840409797707, 'bagging_temperature': 7.504039501626112, 'border_count': 172}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 20:45:39,901] Trial 37 finished with value: 0.8529741863075196 and parameters: {'iterations': 831, 'depth': 10, 'learning_rate': 0.008573201932806114, 'l2_leaf_reg': 2.226733596280139, 'bagging_temperature': 8.987242864500967, 'border_count': 199}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 20:50:16,563] Trial 38 finished with value: 0.8518518518518519 and parameters: {'iterations': 1494, 'depth': 9, 'learning_rate': 0.006433379292036693, 'l2_leaf_reg': 2.0210783995600408, 'bagging_temperature': 7.0785405927872596, 'border_count': 156}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 20:51:48,572] Trial 39 finished with value: 0.8496071829405163 and parameters: {'iterations': 438, 'depth': 9, 'learning_rate': 0.010456673155193802, 'l2_leaf_reg': 2.6680536151318166, 'bagging_temperature': 8.604078817275578, 'border_count': 237}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 20:54:51,791] Trial 40 finished with value: 0.8260381593714927 and parameters: {'iterations': 1243, 'depth': 8, 'learning_rate': 0.17131119381350166, 'l2_leaf_reg': 1.618320931348331, 'bagging_temperature': 6.037450660368957, 'border_count': 220}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 20:59:37,696] Trial 41 finished with value: 0.8484848484848485 and parameters: {'iterations': 816, 'depth': 10, 'learning_rate': 0.008972477468209667, 'l2_leaf_reg': 2.555214504118035, 'bagging_temperature': 8.89656143160411, 'border_count': 206}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 21:04:27,412] Trial 42 finished with value: 0.8518518518518519 and parameters: {'iterations': 863, 'depth': 10, 'learning_rate': 0.007443525439843526, 'l2_leaf_reg': 2.1151253525365674, 'bagging_temperature': 9.614858250394098, 'border_count': 191}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 21:11:02,727] Trial 43 finished with value: 0.8507295173961841 and parameters: {'iterations': 1081, 'depth': 10, 'learning_rate': 0.005995891587959919, 'l2_leaf_reg': 2.938967659858918, 'bagging_temperature': 7.936605345757641, 'border_count': 198}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 21:13:16,451] Trial 44 finished with value: 0.8473625140291807 and parameters: {'iterations': 721, 'depth': 9, 'learning_rate': 0.008009616521331794, 'l2_leaf_reg': 1.3713469327938708, 'bagging_temperature': 6.865948573887679, 'border_count': 186}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 21:18:48,999] Trial 45 finished with value: 0.8439955106621774 and parameters: {'iterations': 948, 'depth': 10, 'learning_rate': 0.015602105979208386, 'l2_leaf_reg': 1.759401178943105, 'bagging_temperature': 8.570369038506222, 'border_count': 163}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 21:21:40,393] Trial 46 finished with value: 0.8496071829405163 and parameters: {'iterations': 662, 'depth': 9, 'learning_rate': 0.005155264917759554, 'l2_leaf_reg': 4.089570884227757, 'bagging_temperature': 7.47911858864822, 'border_count': 232}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 21:23:31,947] Trial 47 finished with value: 0.8496071829405163 and parameters: {'iterations': 886, 'depth': 8, 'learning_rate': 0.010437661458668155, 'l2_leaf_reg': 1.4549449548968003, 'bagging_temperature': 9.04162989350219, 'border_count': 205}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 21:27:55,690] Trial 48 finished with value: 0.8395061728395061 and parameters: {'iterations': 580, 'depth': 10, 'learning_rate': 0.0566208455155581, 'l2_leaf_reg': 2.340520511970759, 'bagging_temperature': 4.949523427498142, 'border_count': 255}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 21:32:48,845] Trial 49 finished with value: 0.8383838383838383 and parameters: {'iterations': 786, 'depth': 9, 'learning_rate': 0.02264615039917186, 'l2_leaf_reg': 1.1072184137135788, 'bagging_temperature': 6.430158585810442, 'border_count': 242}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 21:37:18,955] Trial 50 finished with value: 0.8451178451178452 and parameters: {'iterations': 1071, 'depth': 7, 'learning_rate': 0.03336930576138634, 'l2_leaf_reg': 6.7062435918376595, 'bagging_temperature': 3.952498548663363, 'border_count': 142}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 21:40:54,891] Trial 51 finished with value: 0.8552188552188552 and parameters: {'iterations': 749, 'depth': 7, 'learning_rate': 0.006100049947342891, 'l2_leaf_reg': 1.0263862330045022, 'bagging_temperature': 1.4090883588661027, 'border_count': 243}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 21:44:37,143] Trial 52 finished with value: 0.8552188552188552 and parameters: {'iterations': 823, 'depth': 7, 'learning_rate': 0.006015353354156385, 'l2_leaf_reg': 1.307884384882794, 'bagging_temperature': 1.0769851204655412, 'border_count': 225}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 21:46:29,460] Trial 53 finished with value: 0.8518518518518519 and parameters: {'iterations': 722, 'depth': 7, 'learning_rate': 0.006072810468477575, 'l2_leaf_reg': 1.3469864500074389, 'bagging_temperature': 1.067405633222639, 'border_count': 226}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 21:48:02,232] Trial 54 finished with value: 0.8484848484848485 and parameters: {'iterations': 768, 'depth': 6, 'learning_rate': 0.005818113024695002, 'l2_leaf_reg': 1.09637970961043, 'bagging_temperature': 0.021654057120370718, 'border_count': 243}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 21:52:02,665] Trial 55 finished with value: 0.8473625140291807 and parameters: {'iterations': 906, 'depth': 7, 'learning_rate': 0.005017645126032878, 'l2_leaf_reg': 1.278105004454068, 'bagging_temperature': 1.7028272967167752, 'border_count': 227}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 21:53:55,535] Trial 56 finished with value: 0.8507295173961841 and parameters: {'iterations': 615, 'depth': 8, 'learning_rate': 0.0069930638740337316, 'l2_leaf_reg': 1.024192962204909, 'bagging_temperature': 1.5607184121626596, 'border_count': 236}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 21:55:51,228] Trial 57 finished with value: 0.8507295173961841 and parameters: {'iterations': 949, 'depth': 6, 'learning_rate': 0.011091528755226817, 'l2_leaf_reg': 9.895935525148555, 'bagging_temperature': 1.2198377374895109, 'border_count': 213}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 21:58:12,599] Trial 58 finished with value: 0.8428731762065096 and parameters: {'iterations': 740, 'depth': 5, 'learning_rate': 0.005891427781673737, 'l2_leaf_reg': 1.200297247729257, 'bagging_temperature': 2.0869045590942887, 'border_count': 250}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 22:00:11,706] Trial 59 finished with value: 0.8462401795735129 and parameters: {'iterations': 814, 'depth': 7, 'learning_rate': 0.01436291695375351, 'l2_leaf_reg': 1.4331370063865436, 'bagging_temperature': 0.08648249620811788, 'border_count': 221}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 22:01:29,647] Trial 60 finished with value: 0.8496071829405163 and parameters: {'iterations': 503, 'depth': 8, 'learning_rate': 0.007120256449743554, 'l2_leaf_reg': 1.6674843602142593, 'bagging_temperature': 0.7531689182042847, 'border_count': 246}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 22:02:57,889] Trial 61 finished with value: 0.8552188552188552 and parameters: {'iterations': 854, 'depth': 7, 'learning_rate': 0.008518199356891711, 'l2_leaf_reg': 2.0356954495829562, 'bagging_temperature': 7.890908252530737, 'border_count': 200}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 22:04:29,794] Trial 62 finished with value: 0.8518518518518519 and parameters: {'iterations': 867, 'depth': 7, 'learning_rate': 0.008460976309690647, 'l2_leaf_reg': 1.9354917223821841, 'bagging_temperature': 9.913875957161956, 'border_count': 185}. Best is trial 22 with value: 0.856341189674523.
[I 2026-09-05 22:05:54,967] Trial 63 finished with value: 0.8540965207631874 and parameters: {'iterations': 968, 'depth': 6, 'learning_rate': 0.0055649150855241105, 'l2_leaf_reg': 1.146387438118784, 'bagging_temperature': 7.748722496369767, 'border_count': 211}. Best is trial 22 with value: 0.856341189674523.

In [59]:
print(study_cb.best_params)
print(study_cb.best_value)

{'iterations': 760, 'depth': 7, 'learning_rate': 0.009990468903622285, 'l2_leaf_reg': 1.3717265878688303, 'bagging_temperature': 3.583425469372962, 'border_count': 206}
0.8574635241301908

In [64]:
best_cb = CatBoostClassifier(**study_cb.best_params, random_state=gseed, verbose=0)
_, _, metrics = cv_result(best_cb, X_train, y_train, rskf, preprocessor)
metrics

   TRAIN_acc_MEAN  TRAIN_acc_STD  VAL_acc_MEAN  VAL_acc_STD   OOF_acc
0        0.929667       0.005789      0.846697     0.031033  0.857464

In [65]:
make_submit(
    best_cb, preprocessor, X_train, y_train, df_submit, "best_cb_final_features.csv"
)

Файл успешно сохранен: d:\vs_projects\fp_titanic\data\external\best_cb_final_features.csv

# Лучше всего себя показал LGBM, его скор лидерборда составил 0.78468 > 0.77751 (у catboost)